# Generated by Django 3.2.5 on 2021-08-07 04:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Competitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('lastname', models.CharField(max_length=128)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default=0, max_length=16)),
                ('position', models.IntegerField(default=0)),
                ('competitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.competitor')),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('maxParticipants', models.IntegerField()),
                ('startDate', models.DateField()),
                ('finishDate', models.DateField()),
                ('started', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('tournamentType', models.CharField(choices=[('EL', 'Elimination'), ('LE', 'League')], default='EL', max_length=2)),
                ('competitors', models.ManyToManyField(through='tournament.Participation', to='tournament.Competitor')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='organizer', to='tournament.competitor')),
            ],
        ),
        migrations.AddField(
            model_name='participation',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament'),
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('homeScore', models.IntegerField(null=True)),
                ('guestScore', models.IntegerField(null=True)),
                ('startDate', models.DateTimeField()),
                ('started', models.BooleanField()),
                ('finished', models.BooleanField()),
                ('guestTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guest', to='tournament.competitor')),
                ('homeTeam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home', to='tournament.competitor')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament')),
            ],
        ),
    ]
